# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- staging

pool:
  vmImage: 'macOS-10.13'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

# Android Signing
# Sign and align Android APK files
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk' 
    apksign: true # Optional
    apksignerKeystoreFile: 'vaolo.keystore' # Required when apksign == True
    apksignerKeystorePassword: 'qwerty' # Optional
    apksignerKeystoreAlias: 'tp2.key' # Optional
    apksignerKeyPassword: 'qwerty' # Optional
    apksignerArguments: '--verbose' # Optional
    #apksignerFile: # Optional
    zipalign: true # Optional
    #zipalignFile: # Optional
    
- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'

# Upload apk file to github
- bash: cd $(build.artifactStagingDirectory)/vaolo/vaolo.Android/obj/Release/android/bin &&
        git init &&
        git add . &&
        git commit -m 'Updated .apk' &&
        git push -f https://$(git.login):$(git.password)@github.com/JS-Cormier/vaolo_apk.git master
